export const GrpcErrorMessage = {
    CANCELLED_ERROR: 'CANCELLED_ERROR',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
    INVALID_ARGUMENT_ERROR: 'INVALID_ARGUMENT_ERROR',
    NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
    ALREADY_EXISTS_ERROR: 'ALREADY_EXISTS_ERROR',
    PERMISSION_DENIED_ERROR: 'PERMISSION_DENIED_ERROR',
    ABORTED_ERROR: 'ABORTED_ERROR',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    UNAUTHENTICATED_ERROR: 'UNAUTHENTICATED_ERROR',
} as const